### ISSUE TITLE
[질문] xaquery에 IsNext case에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by killerqueenc** [sculove/xing-plus#5]
t8412의 경우에 cts_date 값을 설정하여서 연속일자를 설정할 수 있습니다.
IsNext가 활성화 되어서 2번째 request가 들어갈 때,
                                        return self.request(input, output, True)
input 값이 아래와 같이 설정 되네요.
input
{'InBlock': {'nday': '0', 'edate': '20160311', 'diclose': '1249000', 'sdate': '', 'highend': '1592000', 'qrycnt': 2000, 'jivolume': '283540', 'ncnt': 1, 'shcode': '005930', 'dilow': '1216000', 'comp_yn': 'Y', 'cts_time': '104600', 'jihigh': '1236000', 's_time': '090000'....................

DevCenter의 cts_data Field 속성이나 TR 모의실행의 내용을 봤을땐, 1번째 OutBlock의 cts_data와 cts_time만, InBlock에 반영되어야 할 것 같습니다.

이렇게 계속 진행 될 경우, 2번째 input을 세팅하는 부분에서 res와 매칭이 되지 않아서 Error가 발생하는데요.
#input setting
		for k,v in self.input.items():
			self.query.SetFieldData(self.type + self.inputName, k, 0, v)

#output setting의 else 부분에 따로 처리가 있어야 하지 않을까요?
			else:
				for col in v.keys():
					v[col] = self.query.GetFieldData(self.type + k, col, 0)
					if self.query.IsNext:
						self.input[col] = v[col]

**Comment by sculove** [comment]
혹시 어떤 TR 인지 알수 있을까요?
아래 예가 있는데
이런식으로 작성한거 맞으시죠?
https://github.com/sculove/xing-plus-app/blob/master/test/test_xaquery.py

**Comment by killerqueenc** [comment]
안녕하세요. 답변 주셨는데, 개인적인 사정으로 인해서 ㅠ.ㅠ
응답이 늦었네요. 죄송합니다.

t8412입니다.
코드는 아래와 같이 작성하였습니다.
        xadata = Query("t8412").request({"InBlock" :{"shcode" : self.shcode, "ncnt" : In_ncnt, "qrycnt" : In_qrycnt, "nday" : '0', "sdate" : "", "edate" : In_edate, "etime" : "", "cts_date" : In_cts_date, "comp_yn" : self.comp_yn}},{
            "OutBlock" : ("shcode", "jisiga", "jihigh", "jilow", "jiclose", "jivolume", "disiga", "dihigh","dilow", "diclose", "highend", "lowend", "cts_date", "cts_time", "s_time", "e_time", "dshmin", "rec_count"),
            "OutBlock1" : DataFrame(columns=("date","time", "open", "high", "low", "close", "jdiff_vol", "value", "jongchk", "rate", "sign"))}
                                        )

위의 Input을 주었을 때, cts_data에 의해서,
xaquery.py의 227번 째 줄이 호출 되고 input이 v[col] : output 값이 설정이 됩니다.
xaquery.py의 232번 째 줄이 호출 되고, input 값으로 ouput값이 설정 되면서 

"SetfieldData : t8412.t8412InBlock.disiga 필드를 찾을 수가 없습니다."
Error 가 발생합니다.

disiga 필드는 OutBlock의 있는 필드 값입니다.

**Comment by sculove** [comment]
@killerqueenc 해당 건은 수정이 가능합니다. 그런데 아쉬운 이야기지만. xing-plus의 개선은 앞으로 힘들것 같습니다.

그 이유는 다음과 같습니다.
 - 실시간 데이터가 느리게 나옵니다.
 - xing api의 실시간 데이터에 대한 사용이 어려워서 저도 만들었지만, 실제 개발을 더이상 진행할수가 없을것 같습니다.

> 만약, 키움 증권을 이용하시고, javascript로의 개발이 편하시다면,
다음 project를 이용하시면 javascript만으로 원하시는 것을 개발할수 있습니다.
https://github.com/sculove/QWebview-plus

제가 만든 프로젝트에서 이렇게 이야기하는 이유는 다음과 같습니다.
 - 실시간 데이터가 바로 전달됩니다.
 - 실시간 데이터 사용이 굉장히 쉽습니다.

그리고 필요하시다면 커뮤터 권한을 드릴수 있습니다.
그럼 즐거운 하루되세요.
